---
title: "POST-WORK SESIÓN 1"
author: "Victor Miguel Terrón Macias"
date: "13/1/2021"
output: pdf_document
---

# POST WORK
Mi nombre es Victor Miguel Terón Macias, presento mi actividad correspondiente con el postwork.

# INSTRUCCIONES

Las instrucciones que presenta el postwork de la sesión 1 eS:

## OBJETIVO

El Postwork tiene como objetivo que practiques los comandos básicos aprendidos durante la sesión, de tal modo que sirvan para reafirmar el conocimiento. Recuerda que la programación es como un deporte en el que se debe practicar, habrá caídas, pero lo importante es levantarse y seguir adelante. Éxito

## REQUISITOS

* Concluir los retos
* Haber estudiado los ejemplos durante la sesión

## DESARROLLO

El siguiente postwork, te servirá para ir desarrollando habilidades como si se tratara de un proyecto que evidencie el progreso del aprendizaje durante el módulo, sesión a sesión se irá desarrollando. A continuación aparecen una serie de objetivos que deberás cumplir, es un ejemplo real de aplicación y tiene que ver con datos referentes a equipos de la liga española de fútbol (recuerda que los datos provienen siempre de diversas naturalezas), en este caso se cuenta con muchos datos que se pueden aprovechar, explotarlos y generar análisis interesantes que se pueden aplicar a otras áreas. Siendo así damos paso a las instrucciones:

1. Importa los datos de soccer de la temporada 2019/2020 de la primera división de la liga española a R, los datos los puedes encontrar en el siguiente enlace: https://www.football-data.co.uk/spainm.php

2. Del data frame que resulta de importar los datos a R, extrae las columnas que contienen los números de goles anotados por los equipos que jugaron en casa (FTHG) y los goles anotados por los equipos que jugaron como visitante (FTAG)

3. Consulta cómo funciona la función table en `R` al ejecutar en la consola ?table

Posteriormente elabora tablas de frecuencias relativas para estimar las siguientes probabilidades:

* La probabilidad (marginal) de que el equipo que juega en casa anote x goles (x = 0, 1, 2, ...)
* La probabilidad (marginal) de que el equipo que juega como visitante anote y goles (y = 0, 1, 2, ...)
* La probabilidad (conjunta) de que el equipo que juega en casa anote x goles y el equipo que juega como visitante anote y goles (x = 0, 1, 2, ..., y = 0, 1, 2, ...)


# REALIZANDO EL POSTWORK

Llevando a cabo las instrucciones tenemos que conocer cual es la fórmula con la que podemos calcular probabilidades marginales, gracias a \LaTeX\ : $$P(A)= \dfrac{eventoquescumplen}{totaleventos}$$
```{r punto1,comment=NA}
#POSTWORK SESION 1-VICTOR MIGUEL TERRON MACIAS
#1.Importa los datos de soccer de la temporada 2019/2020 de la primera división de
# la liga española a R, los datos los puedes encontrar en el siguiente enlace: 
# https://www.football-data.co.uk/spainm.php
datos<-read.csv("https://www.football-data.co.uk/mmz4281/1920/SP1.csv")
#View(datos)

#2.Del data frame que resulta de importar los datos a R, extrae las columnas que 
# contienen los números de goles anotados por los equipos que jugaron en casa 
# (FTHG) y los goles anotados por los equipos que jugaron como visitante (FTAG)
colnames(datos)
#CON ESTO EXTRAIGO LAS COLUMNAS
CASA<-datos$FTHG
EXTE<-datos$FTAG
#MI PLUS DE COMPLEMENTO
EQUIPOCASA<-datos$HomeTeam
EQUIPOEXTERNO<-datos$AwayTeam
extraccion<-data.frame(EQUIPODECASA=EQUIPOCASA,GOLESCASA=CASA,
                       EQUIPOINVITADO=EQUIPOEXTERNO,GOLESEXTERNOS=EXTE)
extraccion
#3.Consulta cómo funciona la función table en R al ejecutar en la consola ?table
#Posteriormente elabora tablas de frecuencias relativas para estimar las
#siguientes probabilidades:
#1.La probabilidad (marginal) de que el equipo que
#juega en casa anote x goles (x = 0, 1, 2, ...) 
#2.La probabilidad (marginal) 
#de que el equipo que juega como visitante anote y goles (y = 0, 1, 2, ...)
#3.La probabilidad (conjunta) de que el equipo que juega en casa anote x goles
#y el equipo que juega como visitante anote y goles 
#(x = 0, 1, 2, ..., y = 0, 1, 2, ...)
##CALCULANDO DE QUE EL EQUIPO DE CASA ANOTE X GOLES
fastercasa=(table(datos$FTHG)/dim(datos)[1])*100
fastercasa
#View(fastercasa)
##CALCULANDO LA PROBABILIDAD DE QUE EL EQUIPO EXTERNO ANOTE X GOLES
fasterexterno=(table(datos$FTAG)/dim(datos)[1])*100
fasterexterno
#View(fasterexterno)
#PROBABILIDADES CONJUNTAS
probconj=(table(datos$FTHG, datos$FTAG)/dim(datos)[1])*100
probconj
#View(probconj)
```

En la carpeta del repositorio adjunto el script solo para revisión.
